#!/usr/bin/perl

# ---   *   ---   *   ---
# deps

package Grammar::test;

  use v5.36.0;
  use strict;
  use warnings;

  use Readonly;
  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/lib/sys/';

  use Style;
  use Chk;

  use lib $ENV{'ARPATH'}.'/lib/';

  use Lang;
  use Grammar;

# ---   *   ---   *   ---
# ROM

BEGIN {

  Readonly our $REGEX=>{

    term=>Lang::nonscap(q[;]),
    nterm=>Lang::nonscap(

      q[;],

      iv     => 1,
      mod    => '+',
      sigws  => 1,

    ),

    num=>qr{\d+},

  };

# ---   *   ---   *   ---

  rule('~<nterm>');
  rule('~*2<num>');
  rule('~<term> &term');

  rule('<num_or_nterm> num nterm');
  rule('<any> &clip num_or_nterm term');

  our @CORE=qw(any);

# ---   *   ---   *   ---
}; # BEGIN

# ---   *   ---   *   ---
# test

my $prog=q[
  1 000 token;
  token;
  1 token;

];

my $ice=Grammar::test->parse($prog);
$ice->{p3}->prich();

# ---   *   ---   *   ---
1; # ret
