#!/usr/bin/perl

# AR-INSTALL
# this script sets up a new AR directory

# once your ARPATH./bin/ is made, you may
# update it through avtomat itself

# ---   *   ---   *   ---
# sanity check

my $root=$ENV{'ARPATH'};if(!$root) {
  print "ARPATH missing from ENV; aborted\n";
  exit;

};

# ---   *   ---   *   ---
# deps
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/avtomat/';
  use avt;

# ---   *   ---   *   ---
# fetch missing deps

{
  my @deps=(
    ['help'   ,'https://github.com/Liebranca/help'   ,undef],
    ['ft8'    ,'https://github.com/Liebranca/ft8'    ,undef],
    ['ce'     ,'https://github.com/Liebranca/ce'    ,undef],

  );avt::depchk "$root",\@deps;

};

# ---   *   ---   *   ---
# package configs

my $avtomat_config;{

  my %config=(

  'BUILD' =>  '.'       ,

  'XCPY'  =>  'avtomat*',
  'LCPY'  =>  'avt.pm'  ,
  'HCPY'  =>  '.'       ,

  'GENS'  =>  '.'       ,
  'LIBS'  =>  '.'       ,
  'INCL'  =>  '.'       ,

  'DEFS'  =>  '.'       ,

  );$avtomat_config=avt::strconfig \%config;

};

# ---   *   ---   *   ---

my $help_config;{

  my %config=(

  'BUILD' =>  '.'       ,

  'XCPY'  =>  'help*'   ,
  'LCPY'  =>  'cash.pm' ,
  'HCPY'  =>  '.'       ,

  'GENS'  =>  '.'       ,
  'LIBS'  =>  '.'       ,
  'INCL'  =>  '.'       ,

  'DEFS'  =>  '.'       ,

  );$help_config=avt::strconfig \%config;

};

# ---   *   ---   *   ---

my $ft8_config;{

  my @deps=(
    ['rw-psf','https://github.com/talamus/rw-psf',undef],

  );avt::depchk "$root/ft8",\@deps;

  my %config=(

  'BUILD' =>  '.'       ,

  'XCPY'  =>  'ft8*,writepsf*',
  'LCPY'  =>  'jojft.pm',
  'HCPY'  =>  '.'       ,

  'GENS'  =>  '.'       ,
  'LIBS'  =>  '.'       ,
  'INCL'  =>  '.'       ,

  'DEFS'  =>  '.'       ,

  );$ft8_config=avt::strconfig \%config;

};

# ---   *   ---   *   ---

my $ce_config;{

  my %config=(

  'BUILD' =>  'x:ce'    ,

  'XCPY'  =>  '.'       ,
  'LCPY'  =>  '.'       ,
  'HCPY'  =>  '.'       ,

  'GENS'  =>  'chartab.h:chartab*,'.
              'keymap.h:keymap*',

  'LIBS'  =>  '.'       ,
  'INCL'  =>  '.'       ,

  'DEFS'  =>  '.'       ,

  );$ce_config=avt::strconfig \%config;

};

# ---   *   ---   *   ---
# install packages

`$root/avtomat/avtomat $root scan avtomat help ft8 ce`;
`$root/avtomat/avtomat $root config avtomat $avtomat_config help $help_config ft8 $ft8_config ce $ce_config`;

print `$root/avtomat/avtomat $root make`;

# generate default font
if(!(-e "$root/fonts")) {
  avt::ex 'ft8',['-g','8,16,24',"$root/ft8/lycon","$root/fonts"],'';

};

# ---   *   ---   *   ---
1; # ret
