#!/usr/bin/perl
# ---   *   ---   *   ---

# deps

  use v5.36.0;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/avtomat/sys/';


  use Arstd::String;
  use Arstd::Array;
  use Arstd::Re;
  use Arstd::IO;

  use Fmat;

# ---   *   ---   *   ---



# ---   *   ---   *   ---
# test A0

#{ my @ar=(0,1,2,undef);
#
#  array_filter(\@ar);
#  say fatdump(\@ar);
#
#};
#
## ---   *   ---   *   ---
## test A1
#
#{ my $ar=Arstd::Array->nit(0,undef,1,2,undef);
#
#  $ar->filter();
#  say fatdump($ar);
#
#};
#
## ---   *   ---   *   ---
## test B0
#
#{ my @ar=(key=>'value',name=>0x24);
#
#  my @keys=array_keys(\@ar);
#  say fatdump(\@keys);
#
#  my @values=array_values(\@ar);
#  say fatdump(\@values);
#
#};
#
## ---   *   ---   *   ---
## test B1
#
#{ my $ar=Arstd::Array->nit(
#    key=>'value',name=>0x24
#
#  );
#
#  my @keys=$ar->nkeys();
#  say fatdump(\@keys);
#
#  my @values=$ar->nvalues();
#  say fatdump(\@values);
#
#};

# ---   *   ---   *   ---
# test C1

#{ my $ar=Arstd::Array->nit(
#    0,1,2,3,4,5
#
#  );
#
#  say fatdump($ar);
#
#  my @popd=$ar->rshift(2);
#  say fatdump($ar);
#  say fatdump(\@popd);
#
#};

# ---   *   ---   *   ---
#
#my $monkas='wololo_%i 'x32;
#box_fstrout($monkas,args=>[0..31]);

# ---   *   ---   *   ---
1; # ret
