#!/usr/bin/perl

# tests various avt functions

# ---   *   ---   *   ---
# deps

  use v5.36.0;
  use strict;
  use warnings;

  use Cwd qw(abs_path);

  use lib $ENV{'ARPATH'}.'/lib/';

  use style;
  use arstd;

  use avt;

# ---   *   ---   *   ---

arstd::unit_test_start('avt::fsys');

# ---   *   ---   *   ---
# checks for file-finding

avt::root(avt::dirof(__FILE__));
arstd::test(

  'eq',

  avt::ffind('avt'),
  abs_path(__FILE__),

  name=>'ffind (root/*)',

);

# ---   *   ---   *   ---

avt::root(q{.});

avt::stinc(avt::dirof(__FILE__));
arstd::test(

  'eq',

  avt::ffind('avt'),
  abs_path(__FILE__),

  name=>'ffind (include/*)',

);

# ---   *   ---   *   ---

avt::stlib($ENV{'ARPATH'}.'/lib/');
arstd::test(

  'eq',

  avt::ffind('-llycon'),
  $ENV{'ARPATH'}.'/lib/liblycon.so',

  name=>'ffind (lib/*)',

);

# ---   *   ---   *   ---

arstd::unit_test_passed();

# ---   *   ---   *   ---
1; # ret
