#!/usr/bin/perl

# tests various avt functions

# ---   *   ---   *   ---
# deps

  use v5.36.0;
  use strict;
  use warnings;

  use Storable;
  use Cwd qw(abs_path);

  use lib $ENV{'ARPATH'}.'/avtomat/sys/';

  use Style;
  use Arstd;

  use Shb7;

  use lib $ENV{'ARPATH'}.'/avtomat/hacks/';
  use lib $ENV{'ARPATH'}.'/avtomat/';

  use Avt;
  use Avt::FFI;

  use Fmat;

# ---   *   ---   *   ---

my $ffi=Avt::FFI->get_instance();
$ffi->lib(Shb7::lib('libbase.so'));
$ffi->attach('fn',['word','word'],'word');

say fn(1,2);

# ---   *   ---   *   ---

#Arstd::unit_test_start('Avt::ffind');
#
## ---   *   ---   *   ---
## checks for file-finding
#
#Shb7::set_root($ENV{'ARPATH'});
#Arstd::test(
#
#  'eq',
#
#  Avt::ffind(Shb7::file('avtomat/tests/avt')),
#  Shb7::rel(abs_path(__FILE__)),
#
#  name=>'ffind (root/*)',
#
#);

# ---   *   ---   *   ---

#Avt::stlib($ENV{'ARPATH'}.'/lib/');
#Arstd::test(
#
#  'eq',
#
#  Avt::ffind('-llycon'),
#  $ENV{'ARPATH'}.'/lib/shb7.pm',
#
#  name=>'ffind (lib/*)',
#
#);

# ---   *   ---   *   ---

#Arstd::unit_test_passed();

# ---   *   ---   *   ---
1; # ret
