#!/usr/bin/perl

# ---   *   ---   *   ---
# deps

package Grammar::test;

  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/lib/sys/';
  use Style;

  use lib $ENV{'ARPATH'}.'/lib/';

  use Lang;
  use parent 'Grammar';

# ---   *   ---   *   ---

my $REGEX={

  term=>Lang::nonscap(q[;]),
  nterm=>Lang::nonscap(

    q[;],

    iv     => 1,
    mod    => '+',
    sigws  => 1,

  ),

  num=>qr{\d+},

};

# ---   *   ---   *   ---

my $NTERM={

  name => 'nterm',
  chld => [{
    name=>$REGEX->{nterm},

  }],

};

my $TERM={
  name => $REGEX->{term},
  fn   => 'term',

};

my $NUM={

  name=>'num',
  chld=>[{name=>$REGEX->{num}}],

};

# ---   *   ---   *   ---

my $NUM_OR_NTERM={

  name => 'ored',
  alt  => 1,

  chld => [$NUM,$NTERM],

};

# ---   *   ---   *   ---

my $ANY={

  name => 'any',
#  fn   => 'clip',

  chld => [$NUM_OR_NTERM,$TERM],

};

# ---   *   ---   *   ---

my $CORE=[$ANY];
my $prog=q[
  0;

];

Grammar::test->mkrules(@$CORE);
my $ice=Grammar::test->parse($prog);

$ice->{p3}->prich();

# ---   *   ---   *   ---
1; # ret
