#!/usr/bin/perl

# ---   *   ---   *   ---
# deps

package Grammar::test;

  use v5.36.0;
  use strict;
  use warnings;

  use Readonly;
  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/lib/sys/';

  use Style;
  use Chk;

  use lib $ENV{'ARPATH'}.'/lib/';

  use Lang;
  use Grammar;

# ---   *   ---   *   ---
# ROM

  Readonly our $REGEX=>{

    term=>Lang::nonscap(q[;]),
    nterm=>Lang::nonscap(

      q[;],

      iv     => 1,
      mod    => '+',
      sigws  => 1,

    ),

    num=>qr{\d+},

  };

# ---   *   ---   *   ---

my $NTERM = rule('~<nterm>');
my $TERM  = rule('~<term> &term');
my $ANY   = rule('<any> &clip nterm term');

# ---   *   ---   *   ---

my $CORE=[$ANY];
my $prog=q[
  token;

];

Grammar::test->mkrules(@$CORE);
my $ice=Grammar::test->parse($prog);

$ice->{p3}->prich();

# ---   *   ---   *   ---
1; # ret
