#!/usr/bin/perl

# Tests the lang module

# ---   *   ---   *   ---

# deps
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/lib/';
  use lang;
  use peso::ops;

# ---   *   ---   *   ---

my $pat=lang::hashpat(peso::ops->def);

my $s="a++;";
if($s=~ m/${pat}/) {
  printf "$1\n";

};



# ---   *   ---   *   ---
