#!/usr/bin/perl
#
# tests Lang && Lang::Def
#
# ---   *   ---   *   ---
# deps

  use v5.36.0;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/avtomat/';
  use lib $ENV{'ARPATH'}.'/avtomat/hacks/';
  use lib $ENV{'ARPATH'}.'/avtomat/sys/';

  use Lang;

  use Lang::Perl;
  use Emit::Perl;

  use Fmat;

# ---   *   ---   *   ---

say Emit::Perl->codewrap(

  'test',
  body=>'heyhey',

  include=>[

    q{Vault 'ARPATH'},

  ],

  define=>[

    q{my $Var}=>0,
    q{my $Sack}=>q{[dkasda,askhakjhr,asdkhakhr]},

  ],

);

# ---   *   ---   *   ---
1; # ret
