#!/usr/bin/perl
#
# Tests my madman filter
#
# ---   *   ---   *   ---

# deps
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/avtomat/';
  use lyperl;

# ---   *   ---   *   ---

clan base;

# ---   *   ---   *   ---

reg attrs;
  char str header '$$$$';

# ---   *   ---   *   ---

clan non;

# ---   *   ---   *   ---

my $obj=base::new(v=>2);
print $obj->header."\n";

# ---   *   ---   *   ---
