#!/usr/bin/perl
#
# Tests my madman filter
#
# ---   *   ---   *   ---

# deps
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/avtomat/';
  use lyperl;

# ---   *   ---   *   ---

my $ar=[0,2,4];
iter $a,\@ar {
  printf "$a\n";

};

# ---   *   ---   *   ---
