#!/usr/bin/perl

# test peso classes

# ---   *   ---   *   ---
# deps

  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/avtomat/sys/';
  use lib $ENV{'ARPATH'}.'/avtomat/hacks/';
  use lib $ENV{'ARPATH'}.'/avtomat/';

  use Style;
  use Arstd;

  use Fmat;
  use Blk;

# ---   *   ---   *   ---

my $mem=[];
my $frame=Blk->new_frame();

my $non=$frame->nit(undef,'non');

$non->grow(64);

$Type::Table->nit(

  'struct',[

    byte=>'a',
    byte=>'b',

    wide=>'c',
    word=>'d',
    long=>'e',

  ],

);

my $type=$Type::Table->{struct};
my $ptr=$non->baptize('beg',$type,0,1);


$ptr->setv(0xFF,0xFF,0xFF,0xFF,0xFF);
$non->prich();

# ---   *   ---   *   ---
