#!/usr/bin/perl

# test peso classes

# ---   *   ---   *   ---
# deps

  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/lib/sys/';

  use Style;
  use Arstd::Bytes;

  use Blk;
  use Type;
  use Fmat;

  use lib $ENV{'ARPATH'}.'/lib/hacks/';
  use lib $ENV{'ARPATH'}.'/lib/';

# ---   *   ---   *   ---

my $frame=Blk->new_frame();
my $non=$frame->nit(undef,'non');

my $type=$Type::Table->nit(

  'struct',[

    byte=>'sigil',

    byte_str=>'dom(7)',
    byte_str=>'id(32)',

    word=>'src,dst,size',

  ],

);

my $ptr=$non->alloc('header',$type,1);

$ptr->strcpy(

  q[@].'PESONET'.':test'

);

my $v=$ptr->{by_name}->[0];
${$v->{src}}=0x1;
${$v->{dst}}=0x2;
${$v->{size}}=0x3;

my $d=$non->decode('header');
my %d=@$d;
say fatdump(\%d);

#say $non->{mem};
#$non->prich();

# ---   *   ---   *   ---
