#!/usr/bin/perl

# test peso execution

# ---   *   ---   *   ---
# deps

  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/avtomat/';
  use peso::rd;

my $exps=peso::rd::mam(

  peso::rd->STR,
  "value_decl x,y 1-(3+2),2,3;"

);

# ---   *   ---   *   ---
