#!/usr/bin/perl

# test peso classes

# ---   *   ---   *   ---
# deps

package main;
  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/lib/sys/';

  use Style;
  use Arstd::Bytes;

  use Blk;
  use Type;
  use Cask;
  use Fmat;

  use lib $ENV{'ARPATH'}.'/lib/hacks/';
  use lib $ENV{'ARPATH'}.'/lib/';

  use Peso::Ipret;

# ---   *   ---   *   ---

my $s=q{$:col 82;>hello$:col 07;>};

say Peso::Ipret::pesc(
  $s,gd=>'ANSI',

);

# ---   *   ---   *   ---

#my $frame=Blk->new_frame();
#my $non=$frame->nit(undef,'non');
#
#my $type=$Type::Table->nit(
#
#  'st',[
#
#    byte_str=>'buf(16)',
#
#  ],
#
#);
#
#my $ptr=$non->alloc('st',$type,4);
#my $cask=Cask->nit($ptr->subdiv());
#
#$ptr=$cask->take();
#$ptr=$cask->take();
#
#$ptr->strcpy('$$$$');
#
#my $d=$type->decode($ptr->rawdata());
#say fatdump($d);

#$non->prich();

# ---   *   ---   *   ---
