#!/usr/bin/perl

# test peso classes

# ---   *   ---   *   ---
# deps

  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/avtomat/sys/';
  use lib $ENV{'ARPATH'}.'/avtomat/hacks/';
  use lib $ENV{'ARPATH'}.'/avtomat/';

  use Style;
  use Arstd;

  use Fmat;
  use Blk;

# ---   *   ---   *   ---

my $mem=[];
my $frame=Blk->new_frame();

my $non=$frame->nit(undef,'non');

my $type=$Type::Table->nit(

  'struct',[

    byte=>'a(5)',
    long=>'b',

  ],

);

my $ptr=$non->alloc('beg0',$type,1);
$ptr->setv((0xBB)x5,0xDE74);
$non->free('beg0');

$type=$Type::Table->nit(

  'struct',[

    wide=>'a(8)',
    long=>'b',

  ],

);

$ptr=$non->alloc('beg0',$type,1);
$non->shrink(1);

$non->prich();

# ---   *   ---   *   ---
