#!/usr/bin/perl

# tests Peso Language Pattern Syntax

# ---   *   ---   *   ---
# deps
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/lib/';

  use lang;
  use langdefs::peso;

  use peso::rd;
  use avt;

#print avt::file_sbl(glob("~/AR/ce/clock.h"));

#my $tree=lang->c->plps_match(
#
#  'c_func_decl',
#  'int* var(int** x,const int* y)'
#
#);
#
#$tree->prich();

# ---   *   ---   *   ---
1; # ret
