#!/usr/bin/perl
#
# Tests usage of standard/blueprint
# module and class routines
#
# ---   *   ---   *   ---
# deps
package test;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/avtomat/';
  use lang;

  use pluts;

# ---   *   ---   *   ---

  use constant {

    AUTHOR=>'IBN-3DILA',

  };

# ---   *   ---   *   ---

my $DEPS={

  q($ENV{'ARPATH'}.'/avtomat/')=>[
    'lang',

  ],
};

my $ATTRS={
  -NAME=>[
    'default_name()',
    'lang::valid_name',

    pluts->ATTR_SET|pluts->ATTR_GET

  ],

  -SYMS=>[
    q({-KEY=>0}),
    0,

    pluts->ATTR_GET|pluts->ATTR_CCH

  ],
};

# ---   *   ---   *   ---

my $CLASS=pluts::MODULE(

  $DEPS,
  $ATTRS

);

open FH,'>',
  $ENV{'ARPATH'}.'/avtomat/test.pm' or die $!;

print FH $CLASS;
close FH;

# ---   *   ---   *   ---
