#!/usr/bin/perl

# oh boi

# ---   *   ---   *   ---

  use lib $ENV{'ARPATH'}.'/lib/';
  use lang;

  use v5.36.0;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/lib/hacks/';
  use inline;

# ---   *   ---   *   ---

my $s="hi           \n";
print length (lang::stripline(

# some comment

  $s))."\n";

# ---   *   ---   *   ---
