#!/usr/bin/perl

# oh boi

# ---   *   ---   *   ---

use lib $ENV{'ARPATH'}.'/lib/hacks/';
use inline {
  $ENV{'ARPATH'}.'/lib/'=>['lang'],

};

my $s="hi           \n";
print length (lang::stripline($s))."\n";

# ---   *   ---   *   ---
