#!/usr/bin/perl

# oh boi

# ---   *   ---   *   ---

use lib $ENV{'ARPATH'}.'/lib/';
use lang;

use lib $ENV{'ARPATH'}.'/lib/hacks/';
use inline;

my $s="hi           \n";
print length (lang::stripline($s))."\n";

# ---   *   ---   *   ---
