#!/usr/bin/perl
#
# object magic
#
# ---   *   ---   *   ---

# deps

  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/avtomat/sys/';

  use Frame;
  use parent 'St';

# ---   *   ---   *   ---

sub hello($class,$frame,@args) {
  map {say $ARG} @args;

};

# ---   *   ---   *   ---
# ROM

  sub Frame_Vars($class) {return {

    -autoload=>{

      'hello'=>\&hello,

    },

  }};

# ---   *   ---   *   ---

my $frame=main->new_frame();
$frame->hello('hiii');

# ---   *   ---   *   ---
1; # ret
