#!/usr/bin/perl
#
# basic IPC
#
# ---   *   ---   *   ---

# deps

  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/avtomat/sys/';

  use Cask;
  use Shb7;

  use Via;
  use Via::Harbor;

# ---   *   ---   *   ---

my $hostname='local';

my $frame=Via->new_frame();
my $net=$frame->nit($hostname);

$net->open();

# ---   *   ---   *   ---
# manager

my $pid=$net->split();
if($pid) {

  # listens for requests
  # shuts down if all harbors closed
  $net->arrivals();
  while(wait!=-1) {};

# ---   *   ---   *   ---
# harbor

} else {

  # get new instance
  my $dst=Via->new_harbor($hostname);

  say "\n",$dst;
  say $dst->{name},"\n";

  $dst=$dst->get_harbor($0);

  say "\n",$dst;
  say $dst->{name},"\n";

  # destroy
  Via->ship(
    $dst->{net}=>'@snk Harbor '.$dst->{idex}

  );

  exit(0);

};

# ---   *   ---   *   ---
1; # ret
