#!/usr/bin/perl
#
# basic IPC
#
# ---   *   ---   *   ---

# deps

  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/avtomat/sys/';

  use Cask;

  use Via;
  use Via::Harbor;

# ---   *   ---   *   ---

my $frame=Via->new_frame();
my $net=$frame->nit('local');

$net->open();

# ---   *   ---   *   ---
# manager

my $pid=$net->split();
if($pid) {

  # listens for requests
  # shuts down if all harbors closed
  $net->arrivals();
  while(wait!=-1) {};

# ---   *   ---   *   ---
# harbor

} else {

  # get new instance
  my $dst=$net->ship(
    $net->{path}=>'@nit Harbor local@chd'

  );

  # destroy
  $net->ship(
    $net->{path}=>'@snk Harbor '.$dst->{idex}

  );

  exit(0);

};

# ---   *   ---   *   ---
1; # ret
