#!/usr/bin/perl
# ---   *   ---   *   ---
# C syntax defs

# ---   *   ---   *   ---
#$:CUT;>

my %CEE=(

  -NAME => 'c',
  -EXT  => '\.([ch](pp|xx)?|C|cc|c\+\+|cu|H|hh|ii?)$',
  -HED  => '-\*-.*\<C(\+\+)?((;|[[:blank:]]).*)?-\*-',

  -MAG  => '^(C|C\+\+) (source|program)',

  -COM  => '//',

# ---   *   ---   *   ---

  -VARS =>[

    [0x04,eiths(

      'auto,extern,inline,restrict,signed,'.
      'union,struct,unsigned,static,typedef,'.

      'const'

    ,1)],

# ---   *   ---   *   ---

    [0x04,eiths(

      'sizeof,offsetof,typedef'

    ,1)],

# ---   *   ---   *   ---

    [0x04,eiths(

      '_(Alignas|Alignof|Atomic|Bool|Complex'.
      '|Generic|Imaginary|Noreturn'.
      '|Static_assert|Thread_local),'.

      'class,explicit,friend,mutable,'.
      'namespace,override,private,'.
      'protected,public,register,'.

      'template,this,typename,'.
      'using,virtual,volatile'

    ,1)],

# ---   *   ---   *   ---

    [0x04,eiths(

      'bool,char,double,float,'.
      'int,float,long,short,void,enum,'.

      '([a-z][a-z_]*'.
      '|(u_?)?int(8|16|32|64))'.

      '_t,'.

      'nihil,vec4,mat4,uint'

    ,1)],

# ---   *   ---   *   ---

    [0x04,eiths(

      'gl_(Position|FragColor)'

    ,1)],

  ],

  -BILTN =>[

  ],

# ---   *   ---   *   ---


  -KEYS =>[

    [0x0D,eiths(

      'if,else,for,while,do,switch,case,default,'.
      'try,throw,catch,operator,new,delete,'.
      'break,continue,goto,return'

    ,1)],

    [0x01,eiths(

      '__attribute__[[:blank:]]*\(\([^)]*\)\)'.

      '|__('.

        'aligned|asm|builtin|hidden'.
        '|inline|packed|restrict|section'.
        '|typeof|weak'.

      ')__'

    ,1)],

  ],

# ---   *   ---   *   ---


);$CEE{-LCOM}=[
  [0x02,eaf($CEE{-COM},0,1)],
  [0x02,delim2('/*','*/',1)],

];

# ---   *   ---   *   ---

my %PS=(

  -PAT => '',
  -STR => '',

  -DST => {},
  

);

# ---   *   ---   *   ---

sub ps {

  my $key=shift;

  while($PS{-STR}=~ m/^\s*(${PS{-PAT}})/sg) {

    if(!$1) {last;};;

    push @{ $PS{-DST}->{$key} },$1;
    $PS{-STR}=~ s/^\s*${PS{-PAT}}\s*//s;

  };

};

# ---   *   ---   *   ---

# in:C code
# returns code matches decl
sub cee_decl {

  my $s=shift;

  my $qualy=$CEE{-VARS}->[0]->[1];
  my $types=$CEE{-VARS}->[3]->[1];
  my $isptr='(\\**\\s+|\\s+\\**)';

  $PS{-PAT}='('.$qualy.')*\s+('.
    $types.$isptr.')('.$_LUN.'*)'.'\s*';

  $PS{-PAT}.=delim2('(',')',1);

  if(!($s=~ m/${ PS{-PAT} }/sg)) {
    return undef;

  };$s=~ s/\n//sg;

  $s=~ m/^(.*)${ PS{-PAT} }/;
  if($1) {$s=~ s/\Q${ 1 }//;};

  $PS{-STR}=$s;


# ---   *   ---   *   ---

  my %d=(

    -FN => {
      -QUAL =>[],
      -TYPE =>[],
      -NAME =>[],

    },-ARGS =>[],

  );my $i=0;while($PS{-STR}) {

    $PS{-DST}=$d{-FN};if($i) {

      push @{ $d{-ARGS} },{
        -QUAL=>[],
        -TYPE=>[],
        -NAME=>[],

      };$PS{-DST}=$d{-ARGS}->[-1];

    };

# ---   *   ---   *   ---

    $PS{-PAT}=$qualy;ps(-QUAL);
    $PS{-PAT}=$types.$isptr;ps(-TYPE);
    $PS{-PAT}=$_LUN.'*';ps(-NAME);

    $PS{-STR}=~ s/^\s*[\(,\)]//sg;$i++;

  };

# ---   *   ---   *   ---

  my $ret=[];
  for my $ar($d{-FN}, @{ $d{-ARGS} }) {

    push @$ret,(

      (join ' ',@{ $ar->{-QUAL} }),
      (join ' ',@{ $ar->{-TYPE} }),
      (join ' ',@{ $ar->{-NAME} })

    );

  };my $test=join '',@$ret;
  if($test=~ m/^\s*$/) {
    return undef;

  };return $ret;

};$CEE{-DECL}=\&cee_decl;

# ---   *   ---   *   ---

$DICT{-CEE}=\%CEE;
